// Per-recipe content for every meal name the plan generator can produce.
// Keyed by the exact strings in planGenerator's MEAL_NAMES — those names are
// part of the deterministic plan contract (completion keys), so entries here
// must track them, never the other way around.
//
// Every image URL was verified live (HTTP 200) and hand-matched to the dish.
// Within a single goal's weekly plan no two meals share an image.

import type { MealSlot } from './planGenerator';

export interface Recipe {
  name: string;
  slot: MealSlot;
  image: string;
  ingredients: string[];
  instructions: string[];
}

const u = (id: string) => `https://images.unsplash.com/photo-${id}?w=600&q=80`;

// Generic per-slot fallbacks for names not in the catalog (and <img onError>).
export const SLOT_FALLBACK_IMAGES: Record<MealSlot, string> = {
  breakfast: u('1493770348161-369560ae357d'),
  lunch: u('1512621776951-a57141f2eefd'),
  dinner: u('1467003909585-2f8a72700288'),
  snack: u('1490645935967-10de6ba17061'),
};

function r(name: string, slot: MealSlot, imageId: string, ingredients: string[], instructions: string[]): Recipe {
  return { name, slot, image: u(imageId), ingredients, instructions };
}

const LIST: Recipe[] = [
  // ── Breakfast · weight loss ──────────────────────────────────────────────
  r('Protein Power Bowl', 'breakfast', '1490645935967-10de6ba17061',
    ['2 soft-boiled eggs', '1/2 avocado, sliced', '1/2 cucumber, ribboned', 'Handful of spinach', '1 slice rye toast', 'Pinch of chili flakes'],
    ['Soft-boil the eggs for 6–7 minutes and halve them.', 'Arrange eggs, avocado, cucumber, and spinach over the toast.', 'Season with salt, pepper, and chili flakes.']),
  r('Green Smoothie Bowl', 'breakfast', '1610970881699-44a5587cabec',
    ['1 cup spinach', '1/2 frozen banana', '1/2 green apple', '1 kiwi', '1 scoop vanilla protein', '3/4 cup almond milk'],
    ['Blend everything until thick and smooth.', 'Pour into a bowl or glass.', 'Top with a few apple or kiwi slices.']),
  r('Egg White Scramble', 'breakfast', '1533089860892-a7c6f0a88666',
    ['4 egg whites + 1 whole egg', '1 slice whole-grain toast', 'Handful of lettuce', '1 tsp olive oil', 'Salt and pepper'],
    ['Whisk the eggs and season lightly.', 'Scramble in olive oil over medium heat until just set.', 'Serve on the toast with the greens on the side.']),
  r('Greek Yogurt Parfait', 'breakfast', '1488477181946-6428a0291777',
    ['1 cup Greek yogurt (0–2%)', '1/2 cup strawberries', '2 tbsp granola', '1 tsp honey', '1 tsp chia seeds'],
    ['Layer yogurt, berries, and granola in a jar.', 'Repeat the layers once more.', 'Finish with honey and chia seeds.']),
  r('Oatmeal with Berries', 'breakfast', '1517673400267-0251440c45dc',
    ['1/2 cup rolled oats', '1 cup water or skim milk', '1/2 cup mixed berries', '1/2 kiwi, sliced', '1 tsp maple syrup'],
    ['Simmer the oats in liquid for 4–5 minutes, stirring.', 'Spoon into a bowl.', 'Top with berries, kiwi, and a drizzle of maple syrup.']),
  r('Avocado Toast', 'breakfast', '1525351484163-7529414344d8',
    ['1 slice sourdough', '1/2 avocado', '1 fried or poached egg', 'Squeeze of lemon', 'Chili flakes'],
    ['Toast the bread and mash the avocado onto it with lemon.', 'Top with the egg.', 'Season with salt, pepper, and chili flakes.']),
  r('Chia Seed Pudding', 'breakfast', '1447078806655-40579c2520d6',
    ['3 tbsp chia seeds', '1 cup almond milk', '1/2 tsp vanilla', '1 tsp honey', 'Sliced pear or berries'],
    ['Stir chia, milk, vanilla, and honey; rest 10 minutes and stir again.', 'Refrigerate at least 2 hours or overnight.', 'Top with fruit before serving.']),

  // ── Breakfast · weight gain ──────────────────────────────────────────────
  r('Hearty Breakfast Bowl', 'breakfast', '1606851094291-6efae152bb87',
    ['2 eggs', '3 rashers bacon', '1 slice buttered toast', '1/2 avocado', 'Salt and pepper'],
    ['Crisp the bacon in a skillet, then fry the eggs in the fat.', 'Plate with toast and avocado.', 'Season generously.']),
  r('Protein Pancakes', 'breakfast', '1567620905732-2d1ec7ab7445',
    ['1 cup oat flour', '1 scoop whey protein', '1 banana', '2 eggs', '1/2 cup milk', 'Maple syrup + banana slices to top'],
    ['Blend flour, protein, banana, eggs, and milk into a batter.', 'Cook small pancakes 2 minutes per side.', 'Stack and top with syrup and banana.']),
  r('Loaded Oatmeal', 'breakfast', '1494390248081-4e521a5940db',
    ['3/4 cup rolled oats', '1 cup whole milk', '1 tbsp peanut butter', '1/2 banana', 'Mixed berries', '1 tbsp chopped nuts'],
    ['Cook the oats in milk until creamy.', 'Stir in the peanut butter.', 'Top with banana, berries, and nuts.']),
  r('Breakfast Burrito', 'breakfast', '1512838243191-e81e8f66f1fd',
    ['1 large tortilla', '2 scrambled eggs', '1/4 cup black beans', '2 tbsp cheese', 'Salsa and red onion'],
    ['Scramble the eggs and warm the beans.', 'Fill the tortilla with eggs, beans, cheese, and salsa.', 'Roll tightly and toast seam-side down for 1 minute.']),
  r('French Toast', 'breakfast', '1484723091739-30a097e8f929',
    ['2 thick slices brioche', '2 eggs', '1/4 cup milk', '1/2 banana + blueberries', 'Maple syrup', 'Butter for the pan'],
    ['Whisk eggs and milk; soak the bread 30 seconds per side.', 'Fry in butter until golden on both sides.', 'Stack with fruit and syrup.']),
  r('Granola Bowl', 'breakfast', '1447078806655-40579c2520d6',
    ['3/4 cup granola', '1 cup whole-milk yogurt', '1 pear, sliced', '1 tbsp honey', '1 tbsp pumpkin seeds'],
    ['Spoon the yogurt into a bowl.', 'Top with granola, pear, and seeds.', 'Drizzle with honey.']),
  r('Power Smoothie', 'breakfast', '1502741224143-90386d7f8c82',
    ['1 cup strawberries', '1 banana', '1 scoop protein powder', '1 tbsp peanut butter', '1 cup whole milk', '1 tsp chia seeds'],
    ['Blend everything until smooth.', 'Pour into a tall glass.', 'Top with chia seeds.']),

  // ── Breakfast · muscle gain ──────────────────────────────────────────────
  r('High-Protein Scramble', 'breakfast', '1466637574441-749b8f19452f',
    ['3 whole eggs', 'Handful of spinach', '4 cherry tomatoes', '3 mushrooms, sliced', '1/2 avocado', 'Chives'],
    ['Sauté mushrooms and tomatoes, then add spinach.', 'Pour in whisked eggs and scramble gently.', 'Serve with avocado and chives.']),
  r('Muscle Builder Bowl', 'breakfast', '1587996597484-04743eeb56b4',
    ['3 scrambled eggs', '1/2 cup cooked rice', 'Steamed broccoli and carrots', '50g smoked chicken', '1 tsp sesame oil'],
    ['Reheat the rice and vegetables.', 'Scramble the eggs and slice the chicken.', 'Assemble in a bowl and finish with sesame oil.']),
  r('Protein Oats', 'breakfast', '1517673400267-0251440c45dc',
    ['3/4 cup oats', '1 scoop whey protein', '1 cup milk', '1/2 banana', 'Berries and kiwi', '1 tbsp almond butter'],
    ['Cook oats in milk, then stir in the protein off the heat.', 'Loosen with a splash of milk if thick.', 'Top with fruit and almond butter.']),
  r('Power Breakfast', 'breakfast', '1533089860892-a7c6f0a88666',
    ['3 eggs', '2 slices whole-grain toast', '2 chicken sausages', 'Grilled tomato', 'Butter'],
    ['Fry the eggs and sausages.', 'Toast and butter the bread.', 'Plate everything with the grilled tomato.']),
  r('Anabolic French Toast', 'breakfast', '1484723091739-30a097e8f929',
    ['3 slices whole-grain bread', '4 egg whites + 1 egg', '1/2 scoop casein or whey', 'Cinnamon', 'Banana + blueberries', 'Sugar-free syrup'],
    ['Whisk eggs with protein powder and cinnamon.', 'Soak the bread and cook in a nonstick pan until golden.', 'Stack with fruit and syrup.']),
  r('Protein Smoothie Bowl', 'breakfast', '1610970881699-44a5587cabec',
    ['1 scoop protein powder', '1 cup spinach', '1 frozen banana', '1 kiwi', '3/4 cup milk', 'Granola to top'],
    ['Blend protein, spinach, banana, kiwi, and milk until thick.', 'Pour into a bowl.', 'Top with granola.']),
  r('Egg & Quinoa Bowl', 'breakfast', '1541519227354-08fa5d50c44d',
    ['2 boiled eggs', '1/2 cup cooked quinoa', '1/2 avocado', 'Wholegrain crackers or toast', 'Lemon and dill'],
    ['Halve the eggs and slice the avocado.', 'Layer quinoa, eggs, and avocado.', 'Finish with lemon, dill, salt, and pepper.']),

  // ── Breakfast · maintain ─────────────────────────────────────────────────
  r('Balanced Breakfast', 'breakfast', '1490645935967-10de6ba17061',
    ['2 eggs any style', '1 slice whole-grain toast', '1/2 avocado', 'Cucumber slices', 'Handful of greens'],
    ['Cook the eggs to your liking.', 'Toast the bread.', 'Plate with avocado, cucumber, and greens.']),
  r('Morning Energy Bowl', 'breakfast', '1519996529931-28324d5a630e',
    ['1/2 cup watermelon', '1 kiwi', '1/2 cup strawberries and cherries', '1/2 cup Greek yogurt', '1 tbsp coconut flakes'],
    ['Cube and slice all the fruit.', 'Spoon yogurt into a bowl and pile the fruit on top.', 'Scatter with coconut flakes.']),
  r('Classic Oatmeal', 'breakfast', '1494390248081-4e521a5940db',
    ['1/2 cup rolled oats', '1 cup milk', '1/2 banana', 'Mixed berries', '1 tsp honey', 'Pinch of cinnamon'],
    ['Simmer oats in milk for 5 minutes.', 'Sweeten with honey and cinnamon.', 'Top with banana and berries.']),
  r('Healthy Start', 'breakfast', '1495214783159-3503fd1b572d',
    ['1 slice seeded toast', '2 tbsp ricotta or yogurt', 'Mixed berries', '1 tsp honey', 'Coffee or tea'],
    ['Toast the bread and spread with ricotta.', 'Top with berries and honey.', 'Serve with your morning drink.']),
  r('Nutritious Breakfast', 'breakfast', '1493770348161-369560ae357d',
    ['1/2 cup muesli', '1 cup yogurt', 'Seasonal fruit', '1 slice fruit toast', '1 tsp jam'],
    ['Combine muesli and yogurt in a bowl.', 'Top with fruit.', 'Serve with the toast on the side.']),
  r('Morning Fuel', 'breakfast', '1506084868230-bb9d95c24759',
    ['3 buttermilk pancakes', '1/2 cup blueberries', '1 tbsp maple syrup', '1 tbsp Greek yogurt'],
    ['Cook the pancakes until bubbles form, then flip.', 'Stack with yogurt between layers.', 'Top with blueberries and syrup.']),
  r('Breakfast Blend', 'breakfast', '1490474418585-ba9bad8fd0ea',
    ['1 apple, sliced', '1/2 cup mixed berries', '1/2 banana', '2 squares dark chocolate', 'Handful of nuts'],
    ['Arrange the sliced fruit on a plate.', 'Add nuts and dark chocolate.', 'Serve with coffee or tea.']),

  // ── Lunch · weight loss ──────────────────────────────────────────────────
  r('Lean & Green Salad', 'lunch', '1607532941433-304659e8198a',
    ['3 cups mixed leaves', '100g grilled chicken breast', 'Cherry tomatoes', '1 tbsp olive oil', 'Lemon juice', 'Fresh herbs'],
    ['Slice the grilled chicken.', 'Toss the leaves, tomatoes, and herbs with oil and lemon.', 'Top with the chicken.']),
  r('Protein Power Lunch', 'lunch', '1604909052743-94e838986d24',
    ['1 can tuna in water', '2 boiled eggs', 'Arugula', 'Cherry tomatoes', '1 tbsp olive oil', 'Capers'],
    ['Drain the tuna and halve the eggs.', 'Arrange over the arugula and tomatoes.', 'Dress with olive oil and capers.']),
  r('Veggie Wrap', 'lunch', '1512838243191-e81e8f66f1fd',
    ['1 whole-wheat tortilla', '2 tbsp hummus', 'Grated carrot and cabbage', 'Cucumber sticks', 'Pickled onion'],
    ['Spread hummus over the tortilla.', 'Pile on the vegetables.', 'Roll tightly and slice in half.']),
  r('Grilled Chicken Bowl', 'lunch', '1543339308-43e59d6b73a6',
    ['120g grilled chicken', '1/2 cup roasted sweet potato', '1/2 avocado', 'Mixed leaves', 'Yogurt-lime dressing'],
    ['Slice the chicken and sweet potato.', 'Build the bowl over the leaves.', 'Drizzle with the dressing.']),
  r('Quinoa Salad', 'lunch', '1512621776951-a57141f2eefd',
    ['3/4 cup cooked quinoa', 'Chickpeas', 'Cherry tomatoes', 'Radish and red cabbage', '1/2 avocado', 'Lemon vinaigrette'],
    ['Fluff the quinoa and season.', 'Arrange the vegetables and chickpeas on top.', 'Finish with avocado and vinaigrette.']),
  r('Soup & Salad', 'lunch', '1476718406336-bb5a9690ee2a',
    ['2 cups pumpkin soup', 'Feta crumbles', 'Pumpkin seeds', 'Small side salad', 'Squeeze of orange'],
    ['Heat the soup until steaming.', 'Top with feta and seeds.', 'Serve with the side salad.']),
  r('Mediterranean Bowl', 'lunch', '1547496502-affa22d38842',
    ['Chopped cucumber and tomato', '1/2 avocado', 'Chickpeas', 'Olives', 'Feta', 'Olive oil and oregano'],
    ['Combine the vegetables and chickpeas.', 'Top with avocado, olives, and feta.', 'Dress with oil and oregano.']),

  // ── Lunch · weight gain ──────────────────────────────────────────────────
  r('Hearty Grain Bowl', 'lunch', '1512058564366-18510be2db19',
    ['1 cup fried rice', '100g shrimp or chicken', 'Peas and peppers', '1 egg', 'Soy sauce', 'Lemon wedge'],
    ['Stir-fry the protein, then the vegetables.', 'Add rice and egg; toss over high heat.', 'Season with soy and finish with lemon.']),
  r('Loaded Sandwich', 'lunch', '1499028344343-cd173ffc68a9',
    ['Seeded burger bun', '120g beef or chicken patty', 'Cheese slice', 'Lettuce and tomato', 'Burger sauce'],
    ['Cook the patty and melt the cheese on top.', 'Toast the bun.', 'Stack with salad and sauce.']),
  r('Power Lunch Plate', 'lunch', '1594041680534-e8c8cdebd659',
    ['150g grilled steak', 'Roasted baby potatoes', 'Green vegetables', '1 tbsp butter', 'Rosemary'],
    ['Roast the potatoes with rosemary.', 'Grill the steak to your liking and rest it.', 'Serve with buttered greens.']),
  r('Protein-Rich Pasta', 'lunch', '1563379926898-05f4575a45d8',
    ['100g spaghetti', '150g shrimp', 'Cherry tomatoes', 'Garlic and chili', 'Olive oil', 'Parsley'],
    ['Cook the pasta al dente.', 'Sauté garlic, chili, and shrimp; add tomatoes.', 'Toss with the pasta, oil, and parsley.']),
  r('Substantial Salad', 'lunch', '1533622597524-a1215e26c0a2',
    ['Burrata or mozzarella', 'Heirloom tomatoes', 'Roasted peppers', 'Rocket', 'Crusty bread', 'Balsamic and olive oil'],
    ['Arrange tomatoes and peppers on a platter.', 'Tear the burrata over the top.', 'Dress and serve with bread.']),
  r('Energy Bowl', 'lunch', '1526318896980-cf78c088247c',
    ['1 portion ramen noodles', '100g pulled pork or chicken', '1 soft egg', 'Greens', 'Broth and soy'],
    ['Heat the broth and cook the noodles.', 'Assemble with the meat and greens.', 'Top with the soft-boiled egg.']),
  r('Filling Wrap', 'lunch', '1504674900247-0877df9cc836',
    ['Lettuce leaves or tortilla', '150g sliced beef', 'Rice noodles or rice', 'Herbs and cashews', 'Hoisin-lime sauce'],
    ['Slice the cooked beef thinly.', 'Fill the wraps with beef, rice, and herbs.', 'Top with cashews and sauce.']),

  // ── Lunch · muscle gain ──────────────────────────────────────────────────
  r('Muscle Building Bowl', 'lunch', '1546069901-ba9599a7e63c',
    ['120g salmon or chicken', '2 boiled eggs', 'Corn and edamame', 'Cucumber and tomato', 'Mixed greens', 'Sesame dressing'],
    ['Cook and flake the protein.', 'Arrange everything over the greens.', 'Finish with sesame dressing.']),
  r('High-Protein Lunch', 'lunch', '1604909052743-94e838986d24',
    ['1 can tuna', '2 boiled eggs', 'Arugula and tomato', 'White beans', 'Olive oil and lemon'],
    ['Combine tuna, beans, and vegetables.', 'Top with halved eggs.', 'Dress with oil and lemon.']),
  r('Anabolic Meal', 'lunch', '1498837167922-ddd27525d352',
    ['150g lean protein of choice', '3/4 cup rice or quinoa', 'Mixed roasted vegetables', 'Fresh salad', '1 tbsp olive oil'],
    ['Portion the protein, carbs, and vegetables meal-prep style.', 'Season each component well.', 'Serve warm or pack for later.']),
  r('Power Plate', 'lunch', '1594041680534-e8c8cdebd659',
    ['180g steak', 'Charred potatoes', 'Steamed greens', 'Chimichurri', 'Sea salt'],
    ['Grill the steak over high heat and rest it.', 'Serve with potatoes and greens.', 'Spoon over the chimichurri.']),
  r('Protein-Packed Lunch', 'lunch', '1529042410759-befb1204b468',
    ['150g turkey or beef meatballs', 'Arugula', 'Tomato sauce', 'Parmesan', 'Wholegrain bread'],
    ['Bake or pan-fry the meatballs.', 'Warm the tomato sauce and coat them.', 'Serve on arugula with parmesan and bread.']),
  r('Strength Bowl', 'lunch', '1556040220-4096d522378d',
    ['120g fresh salmon or tuna', 'Sushi rice', 'Carrot, cucumber, avocado', 'Seaweed and sesame', 'Soy and sriracha mayo'],
    ['Season the rice and let it cool slightly.', 'Slice the fish and vegetables.', 'Assemble the poke bowl and dress it.']),
  r('Recovery Meal', 'lunch', '1568600891621-50f697b9a1c7',
    ['150g baked salmon', 'Citrus segments', 'Quinoa or couscous', 'Green beans', 'Olive oil'],
    ['Bake the salmon at 200°C for 12 minutes.', 'Plate over the grains and beans.', 'Top with citrus and olive oil.']),

  // ── Lunch · maintain ─────────────────────────────────────────────────────
  r('Balanced Lunch Plate', 'lunch', '1476224203421-9ac39bcb3327',
    ['120g white fish', 'Small side salad', '1 slice good bread', 'Yogurt-herb dip', 'Lemon'],
    ['Pan-fry the fish until golden.', 'Plate with salad and bread.', 'Serve with the dip and lemon.']),
  r('Midday Fuel', 'lunch', '1511690656952-34342bb7c2f2',
    ['Chickpeas', 'Roasted peppers and greens', 'Cherry tomatoes', 'Toasted pita', 'Olive oil and za\'atar'],
    ['Warm the chickpeas with the roasted vegetables.', 'Season with za\'atar.', 'Serve with pita.']),
  r('Nutritious Bowl', 'lunch', '1512621776951-a57141f2eefd',
    ['Quinoa or brown rice', 'Chickpeas', 'Avocado', 'Rainbow vegetables', 'Tahini-lemon dressing'],
    ['Layer grains and chickpeas in a bowl.', 'Arrange the vegetables by color.', 'Drizzle with tahini dressing.']),
  r('Healthy Lunch', 'lunch', '1607532941433-304659e8198a',
    ['Green salad base', '100g protein of choice', 'Cucumber and herbs', 'Olive oil vinaigrette', 'Seeds'],
    ['Build the salad over the greens.', 'Add the protein.', 'Dress and finish with seeds.']),
  r('Balanced Meal', 'lunch', '1543339308-43e59d6b73a6',
    ['Roasted sweet potato', '100g chicken or tofu', 'Avocado', 'Leaves and sprouts', 'Yogurt dressing'],
    ['Roast the sweet potato until caramelized.', 'Assemble the bowl with protein and greens.', 'Spoon over the dressing.']),
  r('Lunch Special', 'lunch', '1592417817098-8fd3d9eb14a5',
    ['Tomatoes and mozzarella', 'Torn sourdough croutons', 'Basil', 'Olive oil', 'Balsamic vinegar'],
    ['Tear the tomatoes and mozzarella into a bowl.', 'Toss with croutons and basil.', 'Dress generously.']),
  r('Midday Energy', 'lunch', '1547496502-affa22d38842',
    ['Avocado', 'Cucumber and tomato', 'Chickpeas or lentils', 'Chili and lime', 'Olive oil'],
    ['Chop the vegetables into a bowl.', 'Add the legumes.', 'Dress with chili, lime, and oil.']),

  // ── Dinner · weight loss ─────────────────────────────────────────────────
  r('Light Evening Meal', 'dinner', '1519708227418-c8fd9a32b7a2',
    ['150g salmon fillet', 'Zucchini noodles', 'Cherry tomatoes', 'Garlic', 'Olive oil and lemon'],
    ['Pan-sear the salmon 3–4 minutes per side.', 'Sauté the zoodles with garlic and tomatoes for 2 minutes.', 'Serve with lemon.']),
  r('Lean Protein Plate', 'dinner', '1467003909585-2f8a72700288',
    ['150g salmon or white fish', 'Steamed greens', 'Herb salsa', 'Lemon', 'Olive oil'],
    ['Roast the fish at 200°C for 10–12 minutes.', 'Steam the greens.', 'Finish with herb salsa and lemon.']),
  r('Veggie-Forward Dinner', 'dinner', '1511690656952-34342bb7c2f2',
    ['Chickpeas', 'Roasted seasonal vegetables', 'Leafy greens', 'Spices (cumin, paprika)', 'Yogurt drizzle'],
    ['Roast the vegetables with the spices.', 'Toss with chickpeas and greens.', 'Finish with the yogurt drizzle.']),
  r('Clean Eating Plate', 'dinner', '1494859802809-d069c3b71a8a',
    ['Grilled vegetables', '100g lean protein', 'Small portion of grains', 'Fresh salad', 'Lemon vinaigrette'],
    ['Grill the vegetables and protein.', 'Plate with the grains and salad.', 'Dress lightly.']),
  r('Light & Satisfying', 'dinner', '1568600891621-50f697b9a1c7',
    ['140g baked salmon', 'Citrus segments', 'Green beans', 'Herbs', 'Olive oil'],
    ['Bake the salmon until just cooked.', 'Blanch the beans.', 'Plate with citrus, herbs, and a little oil.']),
  r('Evening Greens', 'dinner', '1540189549336-e6e99c3679fe',
    ['Kale and mixed leaves', 'Shaved carrot and beet', 'Feta', 'Walnuts', 'Balsamic dressing'],
    ['Massage the kale with a little dressing.', 'Toss with the vegetables.', 'Top with feta and walnuts.']),
  r('Mindful Dinner', 'dinner', '1414235077428-338989a2e8c0',
    ['120g white fish or chicken', 'Seasonal vegetables', 'Micro herbs', 'Olive oil', 'Lemon'],
    ['Cook the protein gently.', 'Plate restaurant-style with the vegetables.', 'Finish with herbs, oil, and lemon.']),

  // ── Dinner · weight gain ─────────────────────────────────────────────────
  r('Substantial Dinner', 'dinner', '1615937657715-bc7b4b7962c1',
    ['250g ribeye or tomahawk steak', 'Potato wedges', 'Butter and rosemary', 'Sea salt', 'Green salad'],
    ['Sear the steak hard, basting with butter and rosemary.', 'Rest 5 minutes.', 'Serve with wedges and salad.']),
  r('Hearty Evening Meal', 'dinner', '1432139555190-58524dae6a55',
    ['1 pork chop', 'Roasted potatoes', 'Broccolini', 'Apple or pan sauce', 'Butter'],
    ['Roast the potatoes until crisp.', 'Pan-roast the chop and rest it.', 'Serve with broccolini and the sauce.']),
  r('Power Dinner', 'dinner', '1555939594-58d7cb561ad1',
    ['Mixed grilled meats (chicken, sausage)', 'Grilled corn and peppers', 'Flatbread', 'Dips (yogurt, tomato)'],
    ['Grill the meats over high heat.', 'Char the vegetables alongside.', 'Serve family-style with bread and dips.']),
  r('Filling Plate', 'dinner', '1603133872878-684f208fb84b',
    ['1.5 cups egg fried rice', '100g chicken or shrimp', 'Carrots and spring onion', 'Soy sauce', 'Sesame oil'],
    ['Stir-fry the protein and vegetables.', 'Add rice and egg; toss until coated.', 'Season with soy and sesame oil.']),
  r('Energy Dinner', 'dinner', '1559847844-5315695dadae',
    ['150g shrimp', '1 cup rice', 'Gumbo-style tomato broth', 'Peppers and celery', 'Cajun spice'],
    ['Simmer the broth with vegetables and spice.', 'Add shrimp for the last 4 minutes.', 'Serve over rice.']),
  r('Robust Meal', 'dinner', '1574672280600-4accfa5b6f98',
    ['Roast chicken or turkey', 'Roast vegetables', 'Gravy', 'Mashed potatoes', 'Herbs'],
    ['Roast the bird until juices run clear.', 'Rest before carving.', 'Serve with potatoes, vegetables, and gravy.']),
  r('Satisfying Dinner', 'dinner', '1551782450-a2132b4ba21d',
    ['Beef burger patty', 'Brioche bun', 'Cheese, lettuce, tomato', 'Fries', 'Burger sauce'],
    ['Grill the patty and melt the cheese.', 'Toast the bun and stack the burger.', 'Serve with fries.']),

  // ── Dinner · muscle gain ─────────────────────────────────────────────────
  r('Recovery Dinner', 'dinner', '1467003909585-2f8a72700288',
    ['180g salmon', 'Steamed greens', 'Sweet potato mash', 'Lemon', 'Olive oil'],
    ['Roast the salmon at 200°C for 12 minutes.', 'Mash the sweet potato.', 'Plate with greens, lemon, and oil.']),
  r('Muscle Fuel Plate', 'dinner', '1504674900247-0877df9cc836',
    ['180g sliced beef', 'Lettuce cups', 'Rice noodles', 'Cashews and herbs', 'Soy-lime dressing'],
    ['Sear the beef and slice thinly.', 'Fill lettuce cups with noodles and beef.', 'Top with cashews, herbs, and dressing.']),
  r('Anabolic Dinner', 'dinner', '1615937657715-bc7b4b7962c1',
    ['250g lean steak', 'Baked potato', 'Cottage cheese or Greek yogurt', 'Green vegetables', 'Salt and pepper'],
    ['Sear the steak to medium-rare and rest.', 'Split the baked potato and top with cottage cheese.', 'Serve with greens.']),
  r('Strength Meal', 'dinner', '1432139555190-58524dae6a55',
    ['1 large pork chop or chicken breast', 'Roasted potatoes', 'Broccolini', 'Pan jus', 'Olive oil'],
    ['Roast the potatoes until golden.', 'Cook the protein and rest it.', 'Plate with greens and jus.']),
  r('Protein Power Dinner', 'dinner', '1555939594-58d7cb561ad1',
    ['Mixed grilled chicken and lean sausage', 'Grilled vegetables', 'Rice or flatbread', 'Yogurt dip'],
    ['Grill the proteins in batches.', 'Char the vegetables.', 'Serve with rice and the dip.']),
  r('Growth Plate', 'dinner', '1603133872878-684f208fb84b',
    ['1.5 cups fried rice', '150g chicken', 'Egg', 'Mixed vegetables', 'Soy and sesame'],
    ['Stir-fry chicken, then vegetables and egg.', 'Toss through the rice.', 'Season and serve hot.']),
  r('Evening Recovery', 'dinner', '1519708227418-c8fd9a32b7a2',
    ['170g salmon', 'Zucchini noodles or greens', 'Cherry tomatoes', 'Garlic', 'Olive oil'],
    ['Sear the salmon skin-side first.', 'Sauté the vegetables briefly.', 'Plate together with olive oil.']),

  // ── Dinner · maintain ────────────────────────────────────────────────────
  r('Balanced Dinner', 'dinner', '1473093295043-cdd812d0e601',
    ['100g farfalle pasta', 'Basil pesto', 'Cherry tomatoes', 'Parmesan', 'Rocket'],
    ['Cook the pasta al dente.', 'Toss with pesto and tomatoes.', 'Finish with parmesan and rocket.']),
  r('Evening Nutrition', 'dinner', '1519708227418-c8fd9a32b7a2',
    ['140g salmon', 'Zucchini noodles', 'Tomatoes', 'Garlic and lemon', 'Olive oil'],
    ['Pan-sear the salmon.', 'Sauté the zoodles with garlic.', 'Serve with lemon.']),
  r('Healthy Dinner', 'dinner', '1467003909585-2f8a72700288',
    ['140g fish fillet', 'Steamed seasonal greens', 'Herb dressing', 'Lemon', 'Olive oil'],
    ['Roast or steam the fish.', 'Steam the greens.', 'Dress and serve.']),
  r('Balanced Plate', 'dinner', '1414235077428-338989a2e8c0',
    ['120g protein of choice', 'Half a plate of vegetables', 'Small portion of carbs', 'Herbs', 'Olive oil'],
    ['Cook the protein simply.', 'Fill half the plate with vegetables.', 'Add the carbs and finish with herbs.']),
  r('Nutritious Evening', 'dinner', '1568600891621-50f697b9a1c7',
    ['140g baked salmon', 'Citrus', 'Green beans', 'Couscous', 'Olive oil'],
    ['Bake the salmon.', 'Plate over couscous and beans.', 'Top with citrus segments.']),
  r('Dinner Balance', 'dinner', '1464093515883-ec948246accb',
    ['120g shrimp', 'Light cream or tomato sauce', 'Small pasta or rice portion', 'Herbs', 'Lemon'],
    ['Sauté the shrimp gently.', 'Warm through the sauce.', 'Serve over the pasta with herbs.']),
  r('Evening Fuel', 'dinner', '1512003867696-6d5ce6835040',
    ['White fish pieces', 'Asparagus and greens', 'Light broth', 'Chili and spring onion', 'Rice noodles (optional)'],
    ['Bring the broth to a simmer.', 'Poach the fish and vegetables 4–5 minutes.', 'Finish with chili and spring onion.']),

  // ── Snacks · weight loss ─────────────────────────────────────────────────
  r('Smart Snack', 'snack', '1490474418585-ba9bad8fd0ea',
    ['1 apple, sliced', 'Handful of berries', '5 almonds', '1 square dark chocolate'],
    ['Slice the apple.', 'Plate with berries, almonds, and chocolate.']),
  r('Protein Bite', 'snack', '1517093602195-b40af9688b46',
    ['2 wholegrain crackers', '30g cheese', 'Handful of grapes', 'Few walnuts'],
    ['Arrange crackers, cheese, and fruit on a small board.', 'Eat slowly with water or tea.']),
  r('Healthy Choice', 'snack', '1533622597524-a1215e26c0a2',
    ['Tomato and mozzarella bites', 'Basil', 'Olive oil', 'Cracked pepper'],
    ['Slice tomato and mozzarella.', 'Stack with basil and season.']),
  r('Light Snack', 'snack', '1502741224143-90386d7f8c82',
    ['1 cup strawberries', '1/2 cup kefir or yogurt drink', 'Mint', '1 tsp chia'],
    ['Blend the strawberries with kefir.', 'Pour over ice with mint and chia.']),
  r('Clean Snack', 'snack', '1505576399279-565b52d4ac71',
    ['Layered jar: chickpeas', 'Cucumber and tomato', 'Avocado', 'Lemon dressing'],
    ['Layer everything in a jar, dressing first.', 'Shake before eating.']),
  r('Mindful Bite', 'snack', '1495214783159-3503fd1b572d',
    ['1 rice cake or small toast', '2 tbsp cottage cheese', 'Berries', 'Honey drizzle'],
    ['Spread the cottage cheese.', 'Top with berries and a tiny drizzle of honey.']),
  r('Lean Snack', 'snack', '1505253716362-afaea1d3d1af',
    ['Berry and feta side salad', 'Baby spinach', 'Few pecans', 'Balsamic glaze'],
    ['Toss spinach with berries and feta.', 'Finish with pecans and balsamic.']),

  // ── Snacks · weight gain ─────────────────────────────────────────────────
  r('Energy Boost', 'snack', '1610970881699-44a5587cabec',
    ['1 green smoothie: banana', 'Spinach and kiwi', '1 scoop protein', 'Whole milk', '1 tbsp oats'],
    ['Blend everything until smooth.', 'Drink between meals.']),
  r('Power Snack', 'snack', '1517093602195-b40af9688b46',
    ['Cheese selection', 'Wholegrain crackers', 'Grapes and dried fruit', 'Mixed nuts'],
    ['Build a small snack board.', 'Pair with juice or milk.']),
  r('Calorie Dense Bite', 'snack', '1461009312844-e80697a81cc7',
    ['1 protein brownie or flapjack', 'Handful of walnuts', 'Glass of milk'],
    ['Warm the brownie slightly.', 'Serve with walnuts and milk.']),
  r('Fuel Snack', 'snack', '1490474418585-ba9bad8fd0ea',
    ['Fruit plate: apple, banana, berries', 'Dark chocolate squares', 'Handful of nuts'],
    ['Slice the fruit.', 'Add chocolate and nuts.']),
  r('Growth Snack', 'snack', '1488477181946-6428a0291777',
    ['1 cup full-fat Greek yogurt', 'Strawberries', 'Granola', 'Honey'],
    ['Layer yogurt, fruit, and granola in a jar.', 'Top with honey.']),
  r('Energy Bar', 'snack', '1495214783159-3503fd1b572d',
    ['1 oat-and-nut bar (or berry toast)', 'Coffee or milk', 'Extra berries'],
    ['Serve the bar or toast with berries.', 'Pair with your drink.']),
  r('Power Bite', 'snack', '1541519227354-08fa5d50c44d',
    ['Wholegrain crackers', '1/2 avocado', '1 boiled egg', 'Chili flakes'],
    ['Mash avocado onto the crackers.', 'Top with sliced egg and chili.']),

  // ── Snacks · muscle gain ─────────────────────────────────────────────────
  r('Protein Power Snack', 'snack', '1488477181946-6428a0291777',
    ['1 cup Greek yogurt', 'Strawberries', '1/2 scoop protein stirred in', 'Granola'],
    ['Stir the protein into the yogurt.', 'Layer with fruit and granola.']),
  r('Muscle Fuel', 'snack', '1502741224143-90386d7f8c82',
    ['Strawberry protein shake', '1 banana', '1 scoop whey', 'Milk and ice'],
    ['Blend everything until frothy.', 'Drink within 30 minutes of training.']),
  r('Anabolic Bite', 'snack', '1461009312844-e80697a81cc7',
    ['1 protein brownie', '1 tbsp peanut butter', 'Glass of milk'],
    ['Spread peanut butter on the brownie.', 'Serve with milk.']),
  r('Recovery Snack', 'snack', '1519996529931-28324d5a630e',
    ['Fruit bowl: watermelon, kiwi, cherries', '1 cup cottage cheese or yogurt', 'Coconut flakes'],
    ['Cube the fruit into a bowl.', 'Add the cottage cheese and coconut.']),
  r('Strength Snack', 'snack', '1517093602195-b40af9688b46',
    ['Cheese and wholegrain crackers', 'Mixed nuts', 'Dried figs or grapes'],
    ['Plate the cheese, crackers, and nuts.', 'Add the fruit.']),
  r('Protein Hit', 'snack', '1495214783159-3503fd1b572d',
    ['Toast with ricotta', 'Berries', '1 boiled egg on the side'],
    ['Spread ricotta on the toast and top with berries.', 'Serve with the egg.']),
  r('Muscle Snack', 'snack', '1490474418585-ba9bad8fd0ea',
    ['Fruit plate with nuts', 'Beef jerky or 1 boiled egg', 'Dark chocolate square'],
    ['Combine the fruit and protein on a plate.', 'Finish with the chocolate.']),

  // ── Snacks · maintain ────────────────────────────────────────────────────
  r('Balanced Snack', 'snack', '1488477181946-6428a0291777',
    ['1 cup yogurt', 'Strawberries', 'Granola', 'Honey'],
    ['Layer yogurt, fruit, and granola.', 'Drizzle with honey.']),
  r('Healthy Bite', 'snack', '1502741224143-90386d7f8c82',
    ['Strawberry smoothie', 'Mint', 'Chia seeds'],
    ['Blend strawberries with yogurt or milk.', 'Top with mint and chia.']),
  r('Nutritious Snack', 'snack', '1505576399279-565b52d4ac71',
    ['Layered veggie jar', 'Chickpeas', 'Avocado', 'Lemon dressing'],
    ['Layer the jar with dressing at the bottom.', 'Shake and eat.']),
  r('Energy Snack', 'snack', '1610970881699-44a5587cabec',
    ['Green smoothie: spinach', 'Banana and kiwi', 'Milk of choice'],
    ['Blend until smooth.', 'Serve chilled.']),
  r('Balanced Bite', 'snack', '1541519227354-08fa5d50c44d',
    ['Crackers with avocado', '1 boiled egg', 'Salt and chili'],
    ['Top crackers with avocado and egg.', 'Season and eat.']),
  r('Smart Bite', 'snack', '1447078806655-40579c2520d6',
    ['Small granola bowl', 'Yogurt', 'Sliced pear'],
    ['Spoon yogurt into a small bowl.', 'Top with granola and pear.']),
];

export const RECIPES: Record<string, Recipe> = Object.fromEntries(LIST.map((rec) => [rec.name, rec]));

export function getRecipe(name: string, slot: MealSlot): Recipe {
  return (
    RECIPES[name] ?? {
      name,
      slot,
      image: SLOT_FALLBACK_IMAGES[slot],
      ingredients: ['Lean protein', 'Vegetables', 'Whole grains', 'Healthy fats'],
      instructions: ['Combine the components into a balanced plate.', 'Season well and enjoy.'],
    }
  );
}
